[accesslog]
[api]
  insecure=true
  dashboard=true
  debug=true
[log]
  level="INFO"
[entryPoints]

  [entryPoints.web]
    address = ":80"

  [entryPoints.websecure]
    address = ":443"

[certificatesResolvers]
  [certificatesResolvers.lets-resolver]
    [certificatesResolvers.lets-resolver.acme]
      email = "myemail@mydomain.com"
      storage = "/certs/acme.json"
      [certificatesResolvers.lets-resolver.acme.httpChallenge]
        entryPoint = "web"

[providers.docker]
  # endpoint = "tcp://127.0.0.1:2737"
  # domain = "docker.localhost"
  watch = true
  # filename = "docker.tmpl"
  exposedByDefault = false
  usebindportip = true
  #swarmMode = true
  #swarmModeRefreshSeconds = 15
  #network = "vision-net"
  # Enable docker TLS connection.
  #
  # Optional
  #
  #  [docker.tls]
  #  ca = "/etc/ssl/ca.crt"
  #  cert = "/etc/ssl/docker.crt"
  #  key = "/etc/ssl/docker.key"
  #  insecureSkipVerify = true