version: '2'
services:
  traefik:
    image: traefik:v2.9
    restart: always
    ports:
     - "443:443"
     - "80:80"
     - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - letsencrypt:/certs
      - ./conf/traefik/traefik-letsencrypt.toml:/etc/traefik/traefik.toml

  mongodb:
    image: mongo:4.2.0
    restart: always
    environment:
      - AUTH=yes
      - ADMIN_USER=my-admin-db-user
      - ADMIN_PASS=my-admin-db-password
      - APPLICATION_DATABASE=vision-db
      - APPLICATION_USER=vision-db-user
      - APPLICATION_PASS=vision-db-password
    volumes:
      - vision-db:/data/db
      - ./conf/mongodb:/docker-entrypoint-initdb.d

  vision-server:
    image: algotechinfo/vision-server
    restart: always
    depends_on:
      - keycloak
      - mongodb
    environment:
      MONGO_HOST: mongodb:27017
      MONGO_DB: vision-db
      MONGO_USER: vision-db-user
      MONGO_PWD: vision-db-password
      SMTP_HOST:  #mysmtphost
      SMTP_PORT:  #mysmtpport
      SMTP_SECURE: "false"
      SMTP_FROM:  #myemail
      SMTP_USER:  #mysmtpuser
      SMTP_PASS:  #mysmtppwd
      KEYCLOAK_USER: vision-kc-admin
      KEYCLOAK_PASSWORD: vision-kc-password
      KEYCLOAK_URL: https://${VISION_FQDN}/auth
      DOMAIN_NAME: https://${VISION_FQDN}
      CUSTOMER_KEY: vision-ce
    labels:
      - "traefik.enable=true"
      
      - "traefik.http.routers.socket-server.rule=Host(`${VISION_FQDN}`) && PathPrefix(`/ws`)"
      - "traefik.http.routers.socket-server.tls=true"
      - "traefik.http.routers.socket-server.entrypoints=websecure"
      - "traefik.http.routers.socket-server.tls.certresolver=lets-resolver"
      - "traefik.http.routers.socket-server.service=ws"
      - "traefik.http.services.ws.loadbalancer.server.port=3001"

      - "traefik.http.routers.vision-server.rule=Host(`${VISION_FQDN}`) && PathPrefix(`/api`)"
      - "traefik.http.routers.vision-server.tls=true"
      - "traefik.http.routers.vision-server.entrypoints=websecure"
      - "traefik.http.routers.vision-server.tls.certresolver=lets-resolver"
      - "traefik.http.routers.vision-server.service=api"
      - "traefik.http.routers.vision-server.middlewares=vision-server-api@docker"
      - "traefik.http.services.api.loadbalancer.server.port=3000"

      - "traefik.frontend.passHostHeader=true"
      - "traefik.http.middlewares.vision-server-api.replacepathregex.regex=^/api/(.*)"
      - "traefik.http.middlewares.vision-server-api.replacepathregex.replacement=/$$1"

  keycloak:
    restart: always
    image: algotechinfo/algo-keycloak
    command: start-dev --proxy edge --hostname-admin-url=https://${VISION_FQDN}/auth --hostname-url=https://${VISION_FQDN}/auth --health-enabled=true
    environment:
      KEYCLOAK_ADMIN: vision-kc-admin
      KEYCLOAK_ADMIN_PASSWORD: vision-kc-password
      PROXY_ADDRESS_FORWARDING: "true"
    volumes:
      - vision-kc:/opt/keycloak/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.keycloak.rule=Host(`${VISION_FQDN}`) && PathPrefix(`/auth`)"
      - "traefik.http.routers.keycloak.tls=true"
      - "traefik.http.routers.keycloak.entrypoints=websecure"
      - "traefik.http.routers.keycloak.tls.certresolver=lets-resolver"
      - "traefik.http.routers.keycloak.middlewares=keycloak@docker"
      - "traefik.http.services.keycloak.loadbalancer.server.port=8080"

      - "traefik.frontend.passHostHeader=true"
      - "traefik.http.middlewares.keycloak.replacepathregex.regex=^/auth/(.*)"
      - "traefik.http.middlewares.keycloak.replacepathregex.replacement=/$$1"

  pwa-studio:
    image: algotechinfo/pwa-studio
    restart: always
    volumes:
      - /etc/timezone:/etc/timezone:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pwa-studio.rule=Host(`${VISION_FQDN}`) && PathPrefix(`/studio`)"
      - "traefik.http.routers.pwa-studio.tls=true"
      - "traefik.http.routers.pwa-studio.entrypoints=websecure"
      - "traefik.http.routers.pwa-studio.tls.certresolver=lets-resolver"
      - "traefik.http.services.pwa-studio.loadbalancer.server.port=8080"
      - "traefik.frontend.passHostHeader=true"

  pwa-player:
    restart: always
    image: algotechinfo/pwa-player
    volumes:
      - /etc/timezone:/etc/timezone:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pwa-player.rule=Host(`${VISION_FQDN}`)"
      - "traefik.http.routers.pwa-player.tls=true"
      - "traefik.http.routers.pwa-player.entrypoints=websecure"
      - "traefik.http.routers.pwa-player.tls.certresolver=lets-resolver"
      - "traefik.http.services.pwa-player.loadbalancer.server.port=8080"
      - "traefik.frontend.passHostHeader=true"

volumes:
  vision-db:
  vision-kc:
  letsencrypt: